services:
  nginx:
    container_name: nginx
    build: src/requirements/nginx
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - ./src/web:/var/www/html
    restart: always
  wordpress:
    container_name: wordpress
    build: src/requirements/wordpress
    volumes:
      - ./src/web:/var/www/html
    restart: always
  mariadb:
    container_name: mariadb
    build: src/requirements/mariadb
    restart: always
